#!/bin/bash

# Global Variables
END=$'\e[0m'
CYAN='\033[00;36m'
GREEN='\033[00;32m'
password=""

# Functions
. functions.sh

# TODO automatically input password when asked
info "Type your password"
read -s password

# Installing Homebrew
. homebrew.sh

# Installing Homebrew cask
. homebrew_cask.sh

# Installing Z
. z.sh

# Installing wget
. wget.sh

# Installing NVM
. nvm.sh

# Installing yarn
. yarn.sh

# Installing git
. git.sh

# Installing grep
. grep.sh

# Installing ack
. ack.sh

# Installing ag
. ag.sh

# Installing unrar
. unrar.sh

# Installing Python with pip
. python.sh

# Installing GO
. go.sh

# Installing vim
. vim.sh

# Installing nvim
. nvim.sh

# Installing Docker
. docker.sh

# Installing java
. java.sh

# Installing Maven
. maven.sh

# Installing Gradle
. gradle.sh

# Installing Kotlin
. kotlin.sh

# Installing RVM with Ruby
. rvm.sh

# Installing MySQL
. mysql.sh

# Installing PostgreSQL
. postgresql.sh

# Installing Jetbrains-Toolbox
. jetbrains_toolbox.sh

# Installing Android-Studio
. android_studio.sh

# Installing iTerm2
. iterm.sh

# Installing Google Chrome
. google_chrome.sh

# Installing Google Drive
. google_drive.sh

# Installing Spotify
. spotify.sh

# Installing Telegram-Desktop
. telegram_desktop.sh

# Installing Android File Transfer
. android_file_transfer.sh

# Installing Slack
. slack.sh

# Installing Postman
. postman.sh

# Installing zsh
. zsh.sh

# Installing oh-my-zsh
. oh_my_zsh.sh

# Installing zsh-autosuggestions
. zsh-autosuggestions.sh

# Installing zsh-syntax-highlighting
. zsh-syntax-highlighting.sh

# Installing iterm2-integration
. iterm_integration.sh
